import { WhiteNavBar } from "@/modules/home/ui/components/nav-bar/white-bar";
import {
  ChevronRight,
  CircleSlashIcon,
  MailIcon,
  PlaySquareIcon,
  Plug,
  PlusIcon,
  TextIcon,
  TvIcon,
} from "lucide-react";
import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "哔哩哔哩 (゜-゜)つロ 干杯~-bilibili",
  description: "Generated by create next app",
};
interface Props {
  children: ReactNode;
}
export default function Layout({ children }: Props) {
  return (
    <div className="relative h-fit min-h-screen w-screen bg-neutral-200/50">
      <div className="flex w-screen justify-center">
        <WhiteNavBar></WhiteNavBar>

        <div className="relative top-20 h-[3000px] w-full max-w-[2560px] min-w-[1080px] border-8 border-blue-800 bg-white shadow">
          <div className="flex w-full gap-4 px-26 py-8">
            <div className="min-h-[2048px] w-7/10">
              <div>
                <div className="text-primary font-extrabold">
                  金丝猴下山找村民要食物，吃花生米吃得津津有味，狗子的反应亮了
                </div>
                <div className="flex gap-8 text-xs text-neutral-500">
                  <div className="flex items-center gap-1">
                    <PlaySquareIcon className="w-4"></PlaySquareIcon>3.2万
                  </div>
                  <div className="flex items-center gap-1">
                    <TextIcon></TextIcon>54
                  </div>
                  <span className="flex items-center">2025-03-03 09:30:00</span>
                  <div className="flex items-center gap-1">
                    <CircleSlashIcon className="size-4 text-red-500"></CircleSlashIcon>
                    未经作者授权，禁止转载
                  </div>
                </div>
              </div>
              <div className="flex aspect-video w-full flex-col bg-green-300 text-xs font-bold tracking-tight text-neutral-500">
                <video src="d.mp4"></video>
                <div className="flex items-center justify-between gap-4 bg-white py-2 pl-2">
                  <div className="flex items-center gap-4">
                    <span className="bg-neutral-50/0">
                      3338人正在看，已装填478条弹幕
                    </span>
                    <button>
                      <TvIcon></TvIcon>
                    </button>
                  </div>
                  <div className="flex justify-center">
                    <div className="flex flex-1 justify-end">
                      <div className="overflow-hideen grid h-10 w-full flex-1 grid-cols-9 place-items-start self-end rounded-full bg-transparent">
                        <div className="col-start-1 col-end-2 flex h-full w-full cursor-pointer items-center justify-end rounded-l-lg bg-neutral-200/0 hover:text-sky-400">
                          <span className="flex h-full w-8 items-center rounded-l-lg border-b-2 bg-neutral-200/80 p-2 underline">
                            A
                          </span>
                        </div>
                        <input
                          placeholder="已关闭弹幕"
                          className="col-start-2 col-end-8 h-full w-full border-0 bg-neutral-200/80 outline-0"
                        ></input>
                        <button className="col-start-8 col-end-8 flex h-full w-full cursor-pointer items-center bg-neutral-200/80 text-xs tracking-tighter text-neutral-500 hover:text-sky-400">
                          弹幕礼仪
                          <ChevronRight className="size-3"></ChevronRight>
                        </button>
                        <button className="col-start-9 h-full w-full cursor-pointer rounded-r-lg bg-sky-500 px-4 text-sm font-bold text-white">
                          发送
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="tex-xs top-30 h-[190px] w-full bg-amber-300"></div>
            </div>

            <div className="flex min-h-[2048px] flex-col justify-between">
              <div className="sticky -top-130">
                <div className="gap-2">
                  <div className="flex size-10 items-center justify-center rounded-full bg-amber-600 bg-[url(/banner.png)] text-white">
                    HT
                  </div>
                  <div className="flex flex-col gap-[2px]">
                    <div className="flex gap-2">
                      <div className="font-bold text-red-400">通盘刘妙手</div>
                      <div className="flex items-center gap-1 text-xs font-bold text-neutral-500">
                        <MailIcon className="size-3"></MailIcon>发消息
                      </div>
                    </div>
                    <div className="font-mono text-xs text-neutral-400">
                      商务微信：Amber201306 （添加时请说明具体来意！）
                    </div>
                    <div className="flex justify-between pr-4">
                      <button className="flex items-center gap-[1px] rounded border border-red-500 px-2 py-1 text-xs text-red-500 outline-0">
                        <Plug className="size-4"></Plug>充电
                      </button>
                      <button className="flex items-center rounded bg-sky-500 p-1 px-12 text-xs text-white">
                        <PlusIcon className="size-3"></PlusIcon>关注 115.6万
                      </button>
                    </div>
                  </div>
                </div>
                <div className="h-[100px] bg-amber-500/30">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
                <div className="h-[100px] bg-amber-500/0">asdkfljasd</div>
              </div>
              <div className="h-[1000px] bg-transparent"> </div>
            </div>
            {/* <div className="bg-green-400 p-4">
              
            </div> */}
          </div>
        </div>
      </div>
    </div>
  );
}
