import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "哔哩哔哩 (゜-゜)つロ 干杯~-bilibili",
  description: "Generated by create next app",
};
interface Props {
  children: ReactNode;
}
export default function Layout({ children }: Props) {
  return <div>{children}</div>;
}
